version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: illuminate/container
    versions:
    - 7.30.4
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
  - dependency-name: tightenco/collect
    versions:
    - 8.19.0
