name: Docs Build and Deploy
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      # Build sphinx doc
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "apt-get update -y && pip3 install sphinx sphinx_rtd_theme sphinx_copybutton recommonmark sphinx_markdown_tables --user"
          docs-folder: "docs/"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: netlify-docs
          FOLDER: docs
          CLEAN: true
